# 异常
* throw和throws的区别。
 * throws使用在函数上，后面跟的异常类，可以是多个，用逗号隔开。
 * throw使用在函数内，后面跟的是异常对象。
* Exception中有一个特殊的子类异常RuntimeException运行时异常。如果在函数内容抛出该异常，函数上可以不用声明，编译一样通过。如果字啊函数上声明了该异常，调用者可以不用进行处理，编译一样通过。
* 之所以不用再函数声明，是因为不需要让调用者如处理。当该异常发生，希望程序停止，因为在运行时，出现了无法继续运算的情况。

```java
class Demo{
  int div(int a,int b) throws ArithmeticException{
    return a/b;
  }
}

class ExceptionDemo{
  public static void main(String[] args){
    Demo d = new Demo();
    int x = d.div(4,0);
    System.out.println(x);
  }
}
```
* finally代码块：定义一定执行的代码，通常用于关闭资源。
 * finally只有一种情况不会执行，当执行到System.exit(0);
* 异常常见的格式：

```java
try{

}catch(){

}
```
```java
try{

}catch(){

}finally{

}
```
```java
try{

}finally{

}
```
#### 注意：
* catch是用于处理异常，如果没有catch就代表该异常没有被处理。
* 异常在子父类覆盖中的体现：
 * 子类在覆盖父类时，如果父类的方法抛出异常，那么子类的覆盖方法，只能抛出父类的异常或该异常的子类。
 * 如果父类方法抛出多个异常，那么子类在覆盖该方法时，只能抛出父类异常的子集，就是不能多于父类的异常类。
 * 如果父类或者接口的方法没有异常抛出，那么子类在覆盖方法时，也不可以抛出异常。如果子类方法发生了异常，就必须要进行try处理，绝对不能抛。

> Throwable
>> Error
>>Exception
>>>RuntimeException

* 异常体系的特点：异常体系中的所有类及建立的对象都具备可抛性。也就是说，可以被throw和throws关键字所操作。
* 当函数内容有throw抛出异常对象，并未进行try处理，必须要在函数上声明，否则编译失败。RuntimeException除外。如果函数声明了异常，调用者需要进行处理，处理方法可以throws，可以try。
### 自定义异常：
* 定义类继承Exxception或者RuntimeException
 * 1.为了让该自定义类具备可抛性
 * 2.让该类具备操作异常的共性方法。
* 当要定义自定义异常的信息时，可以使用父类已经定义好的功能。
* 异常信息传递给父类的构造函数。

```java
class MyException extends Exception{
  MyException(String message){
    super(message);
  }
}
```
* 异常的好处：
 * 1.将问题进行封装
 * 2.将正常流程代码和问题处理代码相分离，方便易阅读。
* 异常的处理原则：
 * 1.处理方式有两种：try或者throws
 * 2.调用到抛出异常的功能时，抛出几个，就处理几个。
 * 3.多个catch，父类的catch放到最下面。
 * 4.catch内，需要定义针对性的处理方式，不要简单的定义printstackTrace,输出语句，也不要不写。
    * 当捕获到的异常，本功能处理不了时，可以继续在catch中抛出。

```java
try{
  throw new AExcepton();
}catch(AExcepton e){
  throw e;
}
```
 * 如果该异常处理不了，但并不属于该功能出现的异常，可以将异常转换后，在抛出和该功能相关的异常。

 ```java
 try{
   throw new AExcepton();
 }catch(AExcepton e){
   throw new BException();
 }
 ```
